### ISSUE TITLE
Systemd script failing

### ISSUE THREAD

**Issue by jvalteren** [svenvc/pharo-server-tools#3]
Hi Sven,

I'm trying to use a (modified) version of your pharo-server-tools. I will send a PR soon with changes I've made for Pharo 7, 64-bit and Metacello baselines.

However, I can't get the Systemd script to work. Here is what I get when I try to run my service script:
```
* sputnik.service - Sputnik web application
   Loaded: loaded (/home/jvalteren/pharo/sputnik/systemd.service.script; bad)
   Active: failed (Result: exit-code) since Wed 2019-07-24 16:13:48 CEST; 781ms ago
  Process: 31418 ExecStart=/home/jvalteren/pharo/sputnik/pharo-ctl.sh run-sputnik start sputnik (code=exited, status=0/SUCC
 Main PID: 31426 (code=exited, status=1/FAILURE)

Jul 24 16:13:48 leo systemd[1]: sputnik.service: Service hold-off time over, scheduling restart.
Jul 24 16:13:48 leo systemd[1]: sputnik.service: Scheduled restart job, restart counter is at 5.
Jul 24 16:13:48 leo systemd[1]: Stopped Sputnik web application for DeFi Capital..
Jul 24 16:13:48 leo systemd[1]: sputnik.service: Start request repeated too quickly.
Jul 24 16:13:48 leo systemd[1]: sputnik.service: Failed with result 'exit-code'.
Jul 24 16:13:48 leo systemd[1]: Failed to start Sputnik web application
```

The PID file is removed immediately. Any idea what's going on here?

Kind regards, Jonathan

**Comment by svenvc** [comment]
Hi Jonathan,

systemd is a PIA to debug, last time I had trouble, I consulted the following, esp no 2 helped me:

For future reference:

https://www.digitalocean.com/community/tutorials/systemd-essentials-working-with-services-units-and-the-journal

https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

https://www.linux.com/learn/understanding-and-using-systemd

https://www.golinuxcloud.com/beginners-guide-systemd-tutorial-linux/

this is what I sent to my team.

You probably got some path or directory wrong somewhere ...

HTH,

Sven

**Comment by jvalteren** [comment]
Thanks for the fast response!

Actually, I'm getting a MessageNotUnderstood, but only when running with Systemd (??). Can you make anything out from the following:

```
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: SmalltalkImageInstanceID class>>startUpMessageNotUnderstood: receiver of "wantsLineEndConversion:" is nil
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: UndefinedObject(Object)>>doesNotUnderstand: #wantsLineEndConversion:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript>>initializeStream
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript(NonInteractiveTranscript)>>stream
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript>>stream
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: [ self stream nextPutAll: aCollection ] in NeoConsoleTranscript(NonInteractiveTranscript)>>nextPutAll: in Block: [ self stream nextPutAll: aCollection ]
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: Mutex>>critical:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript(NonInteractiveTranscript)>>critical:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript(NonInteractiveTranscript)>>nextPutAll:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript(NonInteractiveTranscript)>>print:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: [ self
Jul 24 16:47:22 leo pharo-ctl.sh[2146]:         print: anObject;
Jul 24 16:47:22 leo pharo-ctl.sh[2146]:         endEntry ] in NeoConsoleTranscript(NonInteractiveTranscript)>>show: in Block: [ self...
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: Mutex>>critical:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript(NonInteractiveTranscript)>>critical:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript(NonInteractiveTranscript)>>show:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: ByteString(Object)>>logCr:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: ByteString(Object)>>logCr
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NonInteractiveUIManager(CommandLineUIManager)>>inform:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: STCommandLineHandler(Object)>>inform:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: STCommandLineHandler>>handleError:reference:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: [ :e | self handleError: e reference: aReference ] in STCommandLineHandler>>handleErrorsDuring:reference: in Block: [ :e | self handleError: e reference: aReference ]...etc...
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: BlockClosure>>cull:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: Context>>evaluateSignal:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: Context>>handleSignal:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: MessageNotUnderstood(Exception)>>signal
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: UndefinedObject(Object)>>doesNotUnderstand: #wantsLineEndConversion:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript>>initializeStream
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript(NonInteractiveTranscript)>>stream
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: NeoConsoleTranscript>>stream
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: [ self stream nextPutAll: aCollection ] in NeoConsoleTranscript(NonInteractiveTranscript)>>nextPutAll: in Block: [ self stream nextPutAll: aCollection ]
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: BlockClosure>>ensure:
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: [ owner := activeProcess.
Jul 24 16:47:22 leo pharo-ctl.sh[2146]: aBlock
Jul 24 16:47:22 leo pharo-ctl.sh[2146]:         ensure: [ owner := nil ] ] in Mutex>>critical: in Block: [ owner := activeProcess....
Jul 24 16:47:22 leo pharo-ctl.sh[2146]:
```

**Comment by svenvc** [comment]
I am guessing you are doing something like

    (NeoConsoleTranscript onFileNamed: 'server-{1}.log') install.

in your startup script, right ? That seems to fail, not sure why.

You can also run your app/server using pharo-ctl.sh directly, that will still be command line, you'll just take systemd out of it

What Pharo version are you using ?

**Comment by jvalteren** [comment]
See my PR, just created it. Will show you what I'm trying to do.

Running the exact command in the systemd script works fine from a terminal: `/home/jvalteren/pharo/sputnik/pharo-ctl.sh run-sputnik start sputnik` 

Systemd must be doing something else to cause this problem. Maybe it's not running a login shell, so it's missing environment variables? Just guessing here...

**Comment by jvalteren** [comment]
I think this has some relevant answers: https://unix.stackexchange.com/a/339645

I'm thinking the 'Non-interactive shell' and 'No TTY' points might be the cause of the NeoConsole transcript error.

**Comment by svenvc** [comment]
I must say that I have not yet run pharo-server-tools on newer P7+

But if the command line you mention runs, than its must be a systemd issue

Are you sure about the working directory ? You can set that in systemd too.

I will look at you PR later, thanks!

**Comment by svenvc** [comment]
BTW, NeoConsoleTranscript is really simple, it just opens a file for appending, nothing magic.

**Comment by svenvc** [comment]
Also, looking at your PR I see that you are doing

    NonInteractiveTranscript stdout install

Although this should work, I can't say I tested this (in production). 

Just to be sure I would try going back to

    (NeoConsoleTranscript onFileNamed: 'server-{1}.log') install.

**Comment by jvalteren** [comment]
Yes, that occurred to me too after looking into the MessageNotUnderstood in NeoConsole. I forked NeoConsole as well and made some changes to refactor use of code deprecated in Pharo 7. I think that should solve it, but need to do some testing.

Didn't have time to do a PR yet. If you're interested you can check it out at /objectguild/NeoConsole.

Thanks!

**Comment by svenvc** [comment]
I looked at your changes to NeoConsole.

Actually, the class NeoConsoleTranscript should not be used (and should eventually be removed): in Pharo 7 the class DailyNonInteractiveTranscript does the same thing and has fixes.

NeoConsoleTranscript is still there because I needed it in earlier Pharo versions.

**Comment by jvalteren** [comment]
Ah, that is good to hear. I will change that in the project that we're currently working on.

Should I remove the transcript class from NeoConsole and update README to point to DailyNonInteractiveTranscript? I'm happy to do a new PR with that later.

**Comment by jvalteren** [comment]
PS Solved the Systemd issue with a combination of setting `WorkingDirectory=...` and `TimeoutSec=3` (don't know if that's needed anymore) and fixing a typo in my `PIDFile=...` directive ;-)
Thanks again for your help!

**Comment by svenvc** [comment]
No I want to leave it there for my legacy projects.

You could create an issue so that I remember to eventually do it.

I also want to hold out integrating your changes until I no longer need the old code myself, if that is OK for you.

**Comment by svenvc** [comment]
Good, good, typos are a bitch ...

**Comment by jvalteren** [comment]
Sure, no problem of course. I will just start using the DailyNonInteractiveTranscript then.
